<a href="https://colab.research.google.com/github/caffeine110/DevanagariScript_mr/blob/master/minimumEditDistance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
### import dependencies
import numpy as np

### Function to calculate the Levenshtein Matrix
def levenshtein(seq1, seq2):
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros ((size_x, size_y))
    for x in range(size_x):
        matrix [x, 0] = x
    for y in range(size_y):
        matrix [0, y] = y

    for x in range(1, size_x):
        for y in range(1, size_y):
            if seq1[x-1] == seq2[y-1]:
                matrix [x,y] = min(
                    matrix[x-1, y] + 1,
                    matrix[x-1, y-1],
                    matrix[x, y-1] + 1
                )
            else:
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )
    #print (matrix)
    return (matrix, matrix[size_x - 1, size_y - 1])


In [0]:
### Defination to calculate the changes

def minEditDistance(matrix, seq1, seq2):
  size_x, size_y = matrix.shape
  x = size_x-1
  y = size_y-1

  while x<=size_x and x>0 and y<=size_y and y>0:
    print (x,y, matrix[x,y])

    min_value = min(matrix[x-1,y], matrix[x-1,y-1], matrix[x,y-1])
    if matrix[x-1,y-1] == min_value:
      if matrix[x-1, y-1] == matrix[x,y]:
        print("Seq2.char : {} ,  Seq1.char : {}".format(seq2[y-1], seq1[x-1]))
        print("No Change...")
        x = x-1
        y = y-1

      elif matrix[x-1, y-1] == matrix[x,y] -1 :
        print("Seq2.char : {} ,  Seq1.char : {}".format(seq2[y-1], seq1[x-1]))
        print("Update Char : {} To : {}".format(seq2[y-1], seq1[x-1]))
        x = x-1
        y = y-1

    elif matrix[x-1, y] == min_value:
      if matrix[x-1, y] == matrix[x,y] -1:
        print("Seq2.char : {} ,  Seq1.char : {}".format(seq2[y-1], seq1[x-1]))
        print('Charactor : {} : should be Inserted'.format(seq1[x-1]))
        x = x-1
        y = y
      
    elif matrix[x, y-1] == min_value:
      if matrix[x, y-1] == matrix[x,y] -1:
        print("Seq2.char : {} ,  Seq1.char : {}".format(seq2[y-1], seq1[x-1]))
        print("Charactor : {} : should be Deleted...".format(seq2[y-1]))
        x = x
        y = y-1

    print('')
  return(x,y)


In [3]:
#Example 1 :
seq1 = 'test'
seq2 = 'text'

#Example 2 :
### Converting seq2 to seq1
seq1 = 'azced'
seq2 = 'abcdef'


matrix, x_1 = levenshtein(seq1, seq2)
print(matrix)
print("No of changes to Make : ", x_1)

x, y = matrix.shape
print("Shape of Matrix : ", x,y)

r = minEditDistance(matrix, seq1, seq2)

[[0. 1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 2. 3. 4. 5.]
 [2. 1. 1. 2. 3. 4. 5.]
 [3. 2. 2. 1. 2. 3. 4.]
 [4. 3. 3. 2. 2. 2. 3.]
 [5. 4. 4. 3. 2. 3. 3.]]
No of changes to Make :  3.0
Shape of Matrix :  6 7
5 6 3.0
Seq2.char : f ,  Seq1.char : d
Update Char : f To : d

4 5 2.0
Seq2.char : e ,  Seq1.char : e
No Change...

3 4 2.0
Seq2.char : d ,  Seq1.char : c
Charactor : d : should be Deleted...

3 3 1.0
Seq2.char : c ,  Seq1.char : c
No Change...

2 2 1.0
Seq2.char : b ,  Seq1.char : z
Update Char : b To : z

1 1 0.0
Seq2.char : a ,  Seq1.char : a
No Change...



In [4]:
# Example 3 :
word = 'इच्छा'
word = 'विद्यालय'
word = 'अँकरच्या'

#Example 2 :
### Converting seq2 to seq1

seq1 = 'ईश्वरचरणी'
seq2 = 'ईशवचणी'


matrix, x_1 = levenshtein(seq1, seq2)
print(matrix)
print("No of changes to Make : ", x_1)

x, y = matrix.shape
print("Shape of Matrix : ", x,y)

r = minEditDistance(matrix, seq1, seq2)

[[0. 1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 2. 3. 4. 5.]
 [2. 1. 0. 1. 2. 3. 4.]
 [3. 2. 1. 1. 2. 3. 4.]
 [4. 3. 2. 1. 2. 3. 4.]
 [5. 4. 3. 2. 2. 3. 4.]
 [6. 5. 4. 3. 2. 3. 4.]
 [7. 6. 5. 4. 3. 3. 4.]
 [8. 7. 6. 5. 4. 3. 4.]
 [9. 8. 7. 6. 5. 4. 3.]]
No of changes to Make :  3.0
Shape of Matrix :  10 7
9 6 3.0
Seq2.char : ी ,  Seq1.char : ी
No Change...

8 5 3.0
Seq2.char : ण ,  Seq1.char : ण
No Change...

7 4 3.0
Seq2.char : च ,  Seq1.char : र
Charactor : र : should be Inserted

6 4 2.0
Seq2.char : च ,  Seq1.char : च
No Change...

5 3 2.0
Seq2.char : व ,  Seq1.char : र
Charactor : र : should be Inserted

4 3 1.0
Seq2.char : व ,  Seq1.char : व
No Change...

3 2 1.0
Seq2.char : श ,  Seq1.char : ्
Charactor : ् : should be Inserted

2 2 0.0
Seq2.char : श ,  Seq1.char : श
No Change...

1 1 0.0
Seq2.char : ई ,  Seq1.char : ई
No Change...

